# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: 2
updates:
  - package-ecosystem: nuget
    directory: Application/
    target-branch: main
    schedule:
      interval: weekly
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 7
      semver-major-days: 14
      default-days: 7
    groups:
      dotnet-runtime:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Microsoft.AspNetCore.Authentication.JwtBearer"
          - "Microsoft.Extensions.Caching.Memory"
          - "Microsoft.Extensions.Logging.Log4Net.AspNetCore"
      openiddict:
        patterns:
          - "OpenIddict*"
      swashbuckle:
        patterns:
          - "Swashbuckle.AspNetCore*"
      nunit:
        patterns:
          - "NUnit*"
